# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: xenial
language: rust
services: docker
sudo: required

addons:
  apt:
    packages:
      - libssl-dev

env:
  global:
    - CRATE_NAME=mycc

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-musl

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-musl
      rust: nightly
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  # TODO update `api_key.secure`
  # - Create a `public_repo` GitHub token. Go to: https://github.com/settings/tokens/new
  # - Encrypt it: `travis encrypt 0123456789012345678901234567890123456789
  # - Paste the output down here
  api_key:
    secure: "Pb98qff8jQahUYN8djKTYJXpBNGxITpmisR3Fi7fcDXZkCoW1UZl3/sE9r1KaosGxprnop9PgYxLcU8x/h0ezfC/08PVUjVTn3fv4hOOJJ6ZT2ugYOWIzeYEY5XTl+SdwgJiYWuJxdeitkfE/duTJtSFjDVmFpZzA/C67TMGC1vXRge5ZWDE55WuTMtNwBRzmgCd+c17RcPaKryqeDIAMS95FdOLmCkJaizhJ5BcspyAfhYKbDxzLKgDQqDt91ftiiTfGlCOWK2aBhmIO2BZqBK29PiCRrQ4eppWt99AYqY1DqHZXOgZzODAQrlmBLGPPOhsjnDvxHDeI6LAt9klBeIjz/J/v/YVS2Fe1TKNTaTx7TgDCv070KK/vMCI8EUKWrGnGWp2jdvb8m6A6y0YEihPiuiVGpJ0UeZHELEd4VMYvJ5qBUGmfRiv7ALN9PoHzPfxkfW0qdWe8OLwdTf4ziP67+fJ9ZS6gkqV+UkzLlmZKmS2kTbfaBzqa0dGlbYWhbM2yaychjbJuReSZ2VnIUDPasZi17Bc1XWZS5k/xbfiWLuRse8yoyUPtqOKifdeez+U2gfqdekxhL2OszLSyFvDgB0NrslAu7XlIq71EWwmCZmjmeTiMNNXfjUNXPyq8MY/yWfDk/L4S7LOTdnP8g/Y5C2hSCTomBUep34nTYo="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    # TODO Here you can pick which targets will generate binary releases
    # In this example, there are some targets that are tested using the stable
    # and nightly channels. This condition makes sure there is only one release
    # for such targets and that's generated using the stable channel
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # Uncomment the following line for coveralls.io
    cargo tarpaulin -v --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    # Uncomment the following two lines create and upload a report for codecov.io
    # cargo tarpaulin --out Xml
    # bash <(curl -s https://codecov.io/bash)
  fi

cache: cargo
before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin || :
  fi
  # Travis can't cache files that are not readable by "others"
  chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
