[package]
name = "mycc"
version = "0.1.0"
authors = ["gky360 <gky360@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6.1"
failure = "0.1.5"
log = "0.4.6"
structopt = "0.2.15"
strum = "0.15.0"
strum_macros = "0.15.0"

[dev-dependencies]
tempdir = "0.3.7"
